require('dotenv').config();
const axios = require('axios');
const mongoose = require('mongoose');
const Animal = require('./models/Animal');
const connectDB = require('./config/db');

const animalsData = [
    { name: "Lion", scientificName: "Panthera leo", description: "The lion is the second-largest cat in the world, known as the 'King of the Jungle'. Lions live in social groups called prides, consisting of related females, their cubs, and a small number of adult males.", category: "Mammal", status: "Vulnerable", habitat: "Savannas, grasslands, and open woodlands of sub-Saharan Africa", diet: "Carnivore — wildebeest, zebra, buffalo, and antelope", lifespan: "10–14 years in wild", speed: "80 km/h", size: "120–250 kg", funFacts: ["A lion's roar can be heard from up to 8 km away.", "Lions sleep up to 20 hours a day.", "Female lions do about 90% of the pride's hunting.", "A group of lions is called a pride."] },
    { name: "Tiger", scientificName: "Panthera tigris", description: "The tiger is the largest wild cat in the world. No two tigers have the same stripe pattern — it is as unique as a human fingerprint. They are excellent swimmers and solitary hunters.", category: "Mammal", status: "Endangered", habitat: "Tropical forests, grasslands, and mangroves across Asia", diet: "Carnivore — deer, wild boar, and water buffalo", lifespan: "10–15 years in the wild", speed: "65 km/h", size: "100–310 kg", funFacts: ["Tigers are excellent swimmers and love water.", "A tiger's stripes extend to its skin.", "Tigers are solitary with vast territories.", "There are more tigers in US captivity than in the wild."] },
    { name: "Elephant", scientificName: "Loxodonta africana", description: "African elephants are the largest land animals on Earth. They are highly intelligent, live in tight-knit family herds led by a matriarch, and are known for their remarkable memory and deep empathy.", category: "Mammal", status: "Vulnerable", habitat: "Savannas, forests, and deserts across Africa", diet: "Herbivore — grasses, leaves, bark, and fruits", lifespan: "60–70 years", speed: "40 km/h", size: "4,000–7,000 kg", funFacts: ["Elephants can recognize themselves in mirrors.", "They mourn their dead and revisit bones of deceased family.", "An elephant's trunk has over 40,000 muscles.", "Elephants communicate through infrasound felt through their feet."] },
    { name: "Giraffe", scientificName: "Giraffa camelopardalis", description: "The giraffe is the tallest living terrestrial animal on Earth. Its elongated neck allows it to feed on acacia leaves that other animals cannot reach.", category: "Mammal", status: "Vulnerable", habitat: "Savannas and open woodlands of sub-Saharan Africa", diet: "Herbivore — acacia leaves, fruits, and flowers", lifespan: "25 years in the wild", speed: "60 km/h", size: "750–1,270 kg", funFacts: ["Giraffes only need 5–30 minutes of sleep per day.", "A giraffe's tongue is about 45 cm long and bluish-purple.", "Baby giraffes can walk within hours of being born.", "Giraffes have the same number of neck vertebrae as humans — just seven."] },
    { name: "Zebra", scientificName: "Equus quagga", description: "Zebras are African equines with distinctive black-and-white striped coats. Each zebra's stripe pattern is unique. They are highly social animals that live in large herds.", category: "Mammal", status: "Least Concern", habitat: "Grasslands, savannas, and mountains of eastern and southern Africa", diet: "Herbivore — grasses, shrubs, and bark", lifespan: "20–25 years", speed: "65 km/h", size: "300–450 kg", funFacts: ["Zebra stripes may help repel biting flies.", "Foals can stand and walk within 20 minutes of birth.", "Zebras sleep standing up.", "A group of zebras is called a dazzle."] },
    { name: "Kangaroo", scientificName: "Macropus rufus", description: "The red kangaroo is the largest marsupial in the world. Kangaroos are iconic to Australia and the only large animals that use hopping as primary locomotion.", category: "Mammal", status: "Least Concern", habitat: "Arid and semi-arid regions of Australia", diet: "Herbivore — grasses and low shrubs", lifespan: "8–12 years in the wild", speed: "70 km/h", size: "55–90 kg", funFacts: ["A baby joey is the size of a grape at birth.", "Kangaroos cannot walk backwards.", "They use their tail as a fifth limb.", "A group of kangaroos is called a mob."] },
    { name: "Panda", scientificName: "Ailuropoda melanoleuca", description: "The giant panda is one of the world's most beloved animals. Despite being a carnivore, 99% of their diet is bamboo. They are a global symbol of wildlife conservation.", category: "Mammal", status: "Vulnerable", habitat: "Temperate broadleaf forests of central China", diet: "Omnivore — primarily bamboo", lifespan: "15–20 years in the wild", speed: "32 km/h", size: "70–125 kg", funFacts: ["Pandas must eat 12–38 kg of bamboo per day.", "A newborn panda weighs just 90–130 grams.", "Pandas have a false thumb for gripping bamboo.", "Giant pandas are excellent tree climbers."] },
    { name: "Cheetah", scientificName: "Acinonyx jubatus", description: "The cheetah is the fastest land animal on Earth, reaching speeds up to 120 km/h in short bursts. Unlike other big cats, cheetahs purr instead of roar.", category: "Mammal", status: "Vulnerable", habitat: "Open savannas and grasslands of Africa and Iran", diet: "Carnivore — gazelles, impalas, and rabbits", lifespan: "10–12 years in the wild", speed: "120 km/h", size: "21–72 kg", funFacts: ["Cheetahs accelerate from 0 to 100 km/h in 3 seconds.", "Their tear marks reduce sun glare while hunting.", "Cheetahs can turn in mid-air while sprinting.", "After a chase they need 30 minutes to recover."] },
    { name: "Penguin", scientificName: "Aptenodytes forsteri", description: "The emperor penguin is the tallest and heaviest of all penguins. They are uniquely adapted to the Antarctic environment and breed during the Antarctic winter.", category: "Bird", status: "Vulnerable", habitat: "Antarctic ice and surrounding oceans", diet: "Carnivore — fish, squid, and krill", lifespan: "15–20 years in the wild", speed: "30 km/h swimming", size: "22–45 kg", funFacts: ["Emperor penguins dive to depths of 500 meters.", "Males incubate eggs on their feet for 65 days in -60°C.", "Penguins have a gland that converts saltwater to freshwater.", "They huddle in thousands to conserve warmth."] },
    { name: "Dolphin", scientificName: "Delphinus delphis", description: "Common dolphins are highly intelligent social marine mammals known for playful behavior and complex communication using clicks, whistles, and body language.", category: "Mammal", status: "Least Concern", habitat: "Warm and temperate seas worldwide", diet: "Carnivore — fish, squid, and crustaceans", lifespan: "25–30 years", speed: "60 km/h", size: "80–235 kg", funFacts: ["Dolphins sleep with one eye open.", "Each dolphin has a unique whistle name.", "They use echolocation to navigate and find food.", "Dolphins are one of few animals that play for fun."] },
    { name: "Whale", scientificName: "Balaenoptera musculus", description: "The blue whale is the largest animal ever known to exist. Despite their massive size, they feed almost exclusively on tiny krill, consuming up to 4 tons per day.", category: "Mammal", status: "Endangered", habitat: "Open oceans worldwide", diet: "Carnivore — primarily krill", lifespan: "80–90 years", speed: "46 km/h", size: "100,000–150,000 kg", funFacts: ["A blue whale's heart is the size of a small car.", "Their calls reach 188 decibels — louder than a jet engine.", "Calves gain about 90 kg per day from mother's milk.", "Their tongue alone can weigh as much as an elephant."] },
    { name: "Shark", scientificName: "Carcharodon carcharias", description: "The great white shark is the world's largest predatory fish. They are apex predators with extraordinary senses including electroreception and exceptional smell.", category: "Fish", status: "Vulnerable", habitat: "Coastal and offshore waters in all major oceans", diet: "Carnivore — seals, sea lions, and fish", lifespan: "70+ years", speed: "56 km/h", size: "680–1,100 kg", funFacts: ["Great whites detect one drop of blood in 100 liters of water.", "They have rows of teeth — when one falls out another grows.", "Sharks have been on Earth for over 450 million years.", "They must keep swimming to breathe."] },
    { name: "Eagle", scientificName: "Haliaeetus leucocephalus", description: "The bald eagle is North America's largest bird of prey and the national symbol of the United States. Their extraordinary vision makes them among the most skilled avian hunters.", category: "Bird", status: "Least Concern", habitat: "Near large bodies of open water across North America", diet: "Carnivore — fish, waterfowl, and small mammals", lifespan: "20–30 years in the wild", speed: "120–160 km/h diving", size: "3–6.3 kg", funFacts: ["Eagles can spot a rabbit from 3.2 km away.", "Their nests can weigh over a ton after years of use.", "Bald eagles were removed from the endangered list in 2007.", "They mate for life and return to the same nest each year."] },
    { name: "Wolf", scientificName: "Canis lupus", description: "The gray wolf is the largest member of the dog family. Wolves are highly social pack animals that play a crucial role in maintaining ecological balance.", category: "Mammal", status: "Least Concern", habitat: "Forests, tundra, mountains, and grasslands across the Northern Hemisphere", diet: "Carnivore — deer, elk, moose, and smaller mammals", lifespan: "6–8 years in the wild", speed: "60 km/h", size: "23–80 kg", funFacts: ["A wolf pack's territory can span 1,000 square kilometers.", "Wolves communicate through howls heard 10 km away.", "They can eat up to 9 kg of food in a single meal.", "Wolves are the ancestors of all domestic dog breeds."] },
    { name: "Gorilla", scientificName: "Gorilla beringei", description: "The mountain gorilla is the largest living primate, sharing 98.3% of DNA with humans. They are gentle giants living in family groups led by a dominant silverback.", category: "Mammal", status: "Critically Endangered", habitat: "Montane forests of the Virunga volcanoes in Central Africa", diet: "Herbivore — leaves, stems, fruit, and bark", lifespan: "35–40 years in the wild", speed: "40 km/h", size: "100–270 kg", funFacts: ["Gorillas build a new sleeping nest every night.", "They can learn sign language and communicate with humans.", "A silverback's arm span can reach 2.6 meters.", "Gorillas rarely drink — they get moisture from food."] },
    { name: "Koala", scientificName: "Phascolarctos cinereus", description: "Koalas are arboreal marsupials native to Australia. Their specialized digestive system detoxifies the poisonous oils in eucalyptus leaves that most animals cannot eat.", category: "Mammal", status: "Vulnerable", habitat: "Eucalyptus forests and woodlands of eastern Australia", diet: "Herbivore — eucalyptus leaves almost exclusively", lifespan: "13–18 years in the wild", speed: "30 km/h", size: "4–15 kg", funFacts: ["Koalas sleep 18–22 hours a day to conserve energy.", "Koala fingerprints are nearly identical to human fingerprints.", "Baby koalas are born the size of a jelly bean.", "Each koala prefers specific eucalyptus trees."] },
    { name: "Flamingo", scientificName: "Phoenicopterus roseus", description: "The greater flamingo is the most widespread flamingo species. Their iconic pink color comes from carotenoid pigments in their food. They are famous for spectacular synchronized displays.", category: "Bird", status: "Least Concern", habitat: "Saltwater lakes, estuaries, and lagoons across Africa, Asia, and Europe", diet: "Omnivore — algae, brine shrimp, and crustaceans", lifespan: "30–40 years in the wild", speed: "60 km/h flying", size: "2–4 kg", funFacts: ["Flamingos are born white — they turn pink from their diet.", "They can fly up to 600 km in one night.", "Both parents produce crop milk to feed their chick.", "Flamingos stand on one leg to conserve body heat."] },
    { name: "Crocodile", scientificName: "Crocodylus niloticus", description: "The Nile crocodile is Africa's largest freshwater predator. They are ancient survivors having changed little in 200 million years. Despite ferocity, mother crocodiles are remarkably tender with young.", category: "Reptile", status: "Least Concern", habitat: "Rivers, lakes, and marshlands across sub-Saharan Africa", diet: "Carnivore — fish, birds, zebras, and wildebeest", lifespan: "70–100 years", speed: "35 km/h", size: "225–750 kg", funFacts: ["Crocodiles have the strongest bite of any animal.", "They cannot chew and swallow food whole.", "Crocodiles are more closely related to birds than lizards.", "They swallow stones to grind food and regulate buoyancy."] },
    { name: "Octopus", scientificName: "Octopus vulgaris", description: "The common octopus is one of the most intelligent invertebrates on Earth. They have three hearts, blue blood, and can change color and texture in milliseconds.", category: "Invertebrate", status: "Least Concern", habitat: "Ocean floors and coral reefs in tropical and temperate seas worldwide", diet: "Carnivore — crabs, lobsters, shrimp, and fish", lifespan: "1–2 years", speed: "40 km/h jet propulsion", size: "3–10 kg", funFacts: ["Octopuses have three hearts and blue blood.", "They can open jars, solve puzzles, and recognize faces.", "An octopus can squeeze through any hole larger than its beak.", "They can regrow a lost arm completely."] },
    { name: "Polar Bear", scientificName: "Ursus maritimus", description: "The polar bear is the world's largest land carnivore. Perfectly adapted to Arctic life, they are classified as marine mammals. Climate change is the greatest threat to their survival.", category: "Mammal", status: "Vulnerable", habitat: "Arctic sea ice, open water, and coastlines", diet: "Carnivore — primarily ringed and bearded seals", lifespan: "25–30 years in the wild", speed: "40 km/h", size: "350–700 kg", funFacts: ["Polar bear fur is transparent, not white.", "Their skin is jet black to absorb heat.", "They can swim continuously across 100+ km of open water.", "Mothers do not eat for up to 8 months while nursing cubs."] },
    { name: "Chimpanzee", scientificName: "Pan troglodytes", description: "Chimpanzees are our closest living relatives, sharing 98.7% of our DNA. They use tools, have complex social structures, and display cultural behaviors passed between generations.", category: "Mammal", status: "Endangered", habitat: "Tropical forests and savannas of central and West Africa", diet: "Omnivore — fruits, nuts, seeds, insects, and small animals", lifespan: "30–40 years in the wild", speed: "25 km/h", size: "32–60 kg", funFacts: ["Chimps use sticks to extract termites from mounds.", "They can learn hundreds of sign language words.", "Chimpanzees laugh when tickled.", "They make and use tools — once thought unique to humans."] },
    { name: "Rhinoceros", scientificName: "Ceratotherium simum", description: "The white rhinoceros is the largest of the five rhino species. Despite their massive armored appearance, rhinos are generally peaceful herbivores. Their horn is made of keratin.", category: "Mammal", status: "Near Threatened", habitat: "Grasslands and savannas of southern Africa", diet: "Herbivore — grasses, leaves, and shoots", lifespan: "40–50 years", speed: "50 km/h", size: "1,500–2,300 kg", funFacts: ["A rhino's horn is made of keratin, not bone.", "Rhinos wallow in mud to cool down.", "They have poor eyesight but excellent hearing and smell.", "A group of rhinos is called a crash."] },
    { name: "Hippopotamus", scientificName: "Hippopotamus amphibius", description: "The hippopotamus is the third-largest land animal on Earth and one of Africa's most dangerous. Despite their docile appearance, they are highly territorial and aggressive.", category: "Mammal", status: "Vulnerable", habitat: "Rivers, lakes, and wetlands of sub-Saharan Africa", diet: "Herbivore — grasses, primarily grazing at night", lifespan: "40–50 years", speed: "30 km/h", size: "1,500–3,000 kg", funFacts: ["Hippos secrete a natural red sunscreen.", "They can hold their breath underwater for up to 5 minutes.", "Hippos are more closely related to whales than to pigs.", "Despite living in water, hippos walk on the bottom — they cannot swim."] },
    { name: "Alligator", scientificName: "Alligator mississippiensis", description: "The American alligator is a large crocodilian native to the southeastern United States. Once endangered, it has made a remarkable recovery and is now a conservation success story.", category: "Reptile", status: "Least Concern", habitat: "Freshwater swamps, marshes, and lakes of the southeastern USA", diet: "Carnivore — fish, turtles, birds, and mammals", lifespan: "30–50 years in the wild", speed: "30 km/h", size: "180–450 kg", funFacts: ["Alligators can go without food for up to a year.", "Nest temperature determines the sex of their eggs.", "They have been known to use sticks as lures during bird season.", "Their bite force is among the strongest of any living animal."] },
    { name: "Camel", scientificName: "Camelus dromedarius", description: "The dromedary camel is perfectly adapted to desert life. Camels store fat — not water — in their humps, which can be converted to energy and water when food is scarce.", category: "Mammal", status: "Least Concern", habitat: "Deserts and arid regions of North Africa and the Middle East", diet: "Herbivore — dry grasses, grains, and desert plants", lifespan: "40–50 years", speed: "65 km/h", size: "300–690 kg", funFacts: ["Camels can drink up to 200 liters of water in one sitting.", "Their humps store fat converted to water and energy.", "They can survive losing 25% of body weight in water.", "Thick eyelashes and closable nostrils protect them from sandstorms."] },
    { name: "Sloth", scientificName: "Bradypus tridactylus", description: "The three-toed sloth is one of the slowest mammals on Earth. They spend most of their lives hanging upside down in rainforest canopies with a metabolism so slow they barely need to eat.", category: "Mammal", status: "Least Concern", habitat: "Tropical rainforests of Central and South America", diet: "Herbivore — leaves, buds, and tender shoots", lifespan: "20–30 years in the wild", speed: "0.27 km/h", size: "3.5–4.5 kg", funFacts: ["Sloths descend from trees once a week to use the bathroom.", "Algae grows on their fur providing camouflage.", "They can turn their heads 270 degrees.", "Sloths are surprisingly strong swimmers."] },
    { name: "Fox", scientificName: "Vulpes vulpes", description: "The red fox is the most geographically widespread wild member of the Carnivora. They are highly adaptable and thrive in diverse environments from forests to cities.", category: "Mammal", status: "Least Concern", habitat: "Forests, grasslands, and urban areas across the Northern Hemisphere", diet: "Omnivore — rabbits, rodents, birds, berries, and insects", lifespan: "3–4 years in the wild", speed: "50 km/h", size: "2.2–14 kg", funFacts: ["Foxes use the Earth's magnetic field to hunt prey under snow.", "A group of foxes is called a skulk.", "Baby foxes are called kits, cubs, or pups.", "Foxes make over 40 different sounds to communicate."] },
    { name: "Deer", scientificName: "Cervus elaphus", description: "The red deer is one of the largest deer species. Males grow impressive antlers shed and regrown every year. They are iconic symbols of wild forests throughout human culture.", category: "Mammal", status: "Least Concern", habitat: "Forests, grasslands, and moorlands across Europe and Asia", diet: "Herbivore — grasses, heather, bark, and shrubs", lifespan: "10–13 years in the wild", speed: "65 km/h", size: "160–240 kg", funFacts: ["Deer antlers are the fastest growing tissue in the animal kingdom.", "Male deer are called stags, females are hinds.", "Deer can jump up to 3 meters high.", "Fawns have white spots for camouflage in dappled light."] },
    { name: "Moose", scientificName: "Alces alces", description: "The moose is the largest member of the deer family. Males have massive palmate antlers spanning over 1.8 meters. Despite their size, moose are excellent swimmers.", category: "Mammal", status: "Least Concern", habitat: "Boreal and mixed forests of North America, Europe, and Asia", diet: "Herbivore — aquatic plants, willows, and birch", lifespan: "15–25 years", speed: "56 km/h", size: "380–700 kg", funFacts: ["Moose can dive up to 5.5 meters to eat aquatic plants.", "Their antlers can weigh up to 20 kg.", "Moose are solitary except during mating season.", "Calves can outrun a human within days of birth."] },
    { name: "Bison", scientificName: "Bison bison", description: "The American bison is the largest land animal in North America. Once numbering 60 million, they were nearly hunted to extinction but have made a remarkable conservation comeback.", category: "Mammal", status: "Near Threatened", habitat: "Grasslands and prairies of North America", diet: "Herbivore — grasses, sedges, and wildflowers", lifespan: "15–20 years in the wild", speed: "55 km/h", size: "400–900 kg", funFacts: ["Bison can run at 55 km/h despite their massive size.", "They roll in dust to repel insects — called wallowing.", "Bison herds once stretched as far as the eye could see.", "A bison's thick skull withstands powerful headbutts."] },
    { name: "Peacock", scientificName: "Pavo cristatus", description: "The Indian peafowl is one of the most recognizable birds in the world. The male's spectacular tail feathers can span over 1.5 meters and are used in elaborate courtship displays.", category: "Bird", status: "Least Concern", habitat: "Forests and grasslands of the Indian subcontinent", diet: "Omnivore — seeds, insects, small reptiles, and berries", lifespan: "15–20 years in the wild", speed: "16 km/h", size: "3.5–6 kg", funFacts: ["A peacock's tail makes up 60% of its total body length.", "The eye-spots create an illusion of many eyes.", "Peacocks can fly despite their massive tails.", "A group of peacocks is called a muster."] },
    { name: "Parrot", scientificName: "Ara macao", description: "The scarlet macaw is one of the most vividly colored parrots. They are highly intelligent, capable of mimicking human speech and solving complex puzzles.", category: "Bird", status: "Least Concern", habitat: "Humid tropical forests of Central and South America", diet: "Omnivore — seeds, nuts, fruits, and insects", lifespan: "40–50 years in the wild", speed: "56 km/h", size: "0.9–1.1 kg", funFacts: ["Scarlet macaws mate for life.", "They can mimic dozens of human words and phrases.", "Their beaks crack open hard palm nuts.", "Macaws eat clay to neutralize food toxins."] },
    { name: "Ostrich", scientificName: "Struthio camelus", description: "The ostrich is the world's largest and heaviest bird. Although it cannot fly, it is the fastest running bird on Earth and its powerful legs can deliver a kick strong enough to kill a lion.", category: "Bird", status: "Least Concern", habitat: "Savannas and arid regions of Africa", diet: "Omnivore — seeds, shrubs, grass, fruit, and insects", lifespan: "40–45 years in the wild", speed: "70 km/h", size: "63–145 kg", funFacts: ["Ostrich eggs are the largest eggs of any living bird.", "They do not bury their heads in the sand — that's a myth.", "An ostrich's eye is bigger than its brain.", "They maintain 50 km/h speeds for up to 30 minutes."] },
    { name: "Swan", scientificName: "Cygnus olor", description: "The mute swan is one of the heaviest flying birds. They form lifelong pair bonds and are fierce protectors of their nests and young.", category: "Bird", status: "Least Concern", habitat: "Lakes, rivers, and coastal waters of Europe and Asia", diet: "Herbivore — aquatic plants, algae, and occasionally insects", lifespan: "20–30 years", speed: "95 km/h flying", size: "7–14 kg", funFacts: ["Swans mate for life and grieve when their partner dies.", "A group of swans is called a bevy.", "Baby swans are called cygnets.", "Swans can be aggressive and capable of breaking a human arm."] },
    { name: "Turtle", scientificName: "Chelonia mydas", description: "The green sea turtle is one of the largest sea turtles. They are remarkable navigators, returning to the exact beach where they were born to lay eggs, sometimes traveling thousands of kilometers.", category: "Reptile", status: "Endangered", habitat: "Tropical and subtropical coastal waters worldwide", diet: "Herbivore — sea grasses and algae", lifespan: "80+ years", speed: "35 km/h swimming", size: "68–190 kg", funFacts: ["Sea turtles use the Earth's magnetic field to navigate.", "They can hold their breath for up to 7 hours while resting.", "Green turtles get their name from the green fat beneath their shell.", "Females return to the same birth beach to lay eggs."] },
    { name: "Snake", scientificName: "Python reticulatus", description: "The reticulated python is the world's longest snake. These powerful constrictors are found in Southeast Asian rainforests and are skilled swimmers.", category: "Reptile", status: "Least Concern", habitat: "Rainforests, woodlands, and grasslands of Southeast Asia", diet: "Carnivore — mammals and birds", lifespan: "20–25 years", speed: "1.6 km/h", size: "Up to 75 kg", funFacts: ["Reticulated pythons can reach over 6 meters in length.", "They smell with their tongues, picking up chemical signals.", "Snakes shed their skin several times a year.", "Pythons can go months without food after a large meal."] },
    { name: "Frog", scientificName: "Dendrobates azureus", description: "The blue poison dart frog is one of the most toxic animals on Earth. Its brilliant blue skin warns predators of the deadly poison it carries, used by indigenous people on blowgun darts.", category: "Amphibian", status: "Vulnerable", habitat: "Tropical rainforests of Suriname and Brazil", diet: "Carnivore — ants, termites, and small insects", lifespan: "4–6 years in the wild", speed: "N/A", size: "3–4.5 grams", funFacts: ["Their toxins are strong enough to kill 10 adult humans.", "In captivity they lose their toxicity due to diet change.", "Fathers carry tadpoles on their backs to water.", "Their bright colors warn predators of danger."] },
    { name: "Seal", scientificName: "Mirounga leonina", description: "The southern elephant seal is the largest of all seals. Males can weigh up to 2,200 kg and spend most of their lives at sea, diving to extraordinary depths.", category: "Mammal", status: "Least Concern", habitat: "Sub-Antarctic and Antarctic waters and islands", diet: "Carnivore — fish and squid", lifespan: "20–22 years", speed: "30 km/h swimming", size: "400–2,200 kg", funFacts: ["Elephant seals dive to depths of 1,500 meters.", "They can hold their breath for up to 2 hours.", "Males fight fiercely for territory.", "They shed their fur and outer skin layer each year."] },
    { name: "Otter", scientificName: "Enhydra lutris", description: "The sea otter is the heaviest member of the weasel family. They use rocks to crack open shellfish and are a keystone species in kelp forest ecosystems.", category: "Mammal", status: "Endangered", habitat: "Coastal waters of the northern and eastern Pacific Ocean", diet: "Carnivore — sea urchins, clams, crabs, and snails", lifespan: "15–20 years", speed: "9 km/h swimming", size: "14–45 kg", funFacts: ["Sea otters hold hands while sleeping to avoid drifting apart.", "They have the densest fur of any animal.", "Otters keep a favorite rock in a pouch under their arm.", "A group of otters is called a raft."] },
    { name: "Beaver", scientificName: "Castor canadensis", description: "The North American beaver is nature's engineer. By building dams and lodges, they create wetland ecosystems benefiting hundreds of species. They are the second-largest rodent in the world.", category: "Mammal", status: "Least Concern", habitat: "Rivers, streams, and lakes across North America", diet: "Herbivore — bark, twigs, and aquatic plants", lifespan: "10–15 years in the wild", speed: "8 km/h swimming", size: "11–32 kg", funFacts: ["Beaver teeth are orange due to iron-rich enamel.", "A beaver can fell a small tree in under 15 minutes.", "Their dams can be over 100 meters long.", "Beavers are monogamous and mate for life."] },
    { name: "Walrus", scientificName: "Odobenus rosmarus", description: "The walrus is a large marine mammal with distinctive long tusks and great bulk. They are highly social animals gathering in large herds on Arctic ice floes.", category: "Mammal", status: "Vulnerable", habitat: "Arctic and sub-Arctic seas and coastlines", diet: "Carnivore — clams, mussels, and mollusks", lifespan: "40 years", speed: "35 km/h swimming", size: "600–1,500 kg", funFacts: ["Walrus tusks can grow up to 1 meter long.", "They use whiskers to detect shellfish on the ocean floor.", "Walruses can slow their heartbeat in icy water.", "A walrus can sleep floating in the ocean."] },
    { name: "Seahorse", scientificName: "Hippocampus kuda", description: "The seahorse is one of the most unique fish in the ocean — the only species where the male becomes pregnant and gives birth. They swim upright and anchor with their prehensile tail.", category: "Fish", status: "Vulnerable", habitat: "Shallow tropical and temperate saltwater worldwide", diet: "Carnivore — small crustaceans and zooplankton", lifespan: "1–5 years", speed: "1.5 km/h", size: "Up to 14 grams", funFacts: ["Male seahorses carry and give birth to the young.", "They can change color to camouflage themselves.", "Seahorses mate for life and greet each other daily.", "They have no stomach so must eat constantly."] },
    { name: "Jellyfish", scientificName: "Turritopsis dohrnii", description: "The immortal jellyfish is technically biologically immortal. When stressed or aging, it reverts back to its juvenile polyp stage and restarts its life cycle — the only known animal capable of this.", category: "Invertebrate", status: "Least Concern", habitat: "Temperate to tropical ocean waters worldwide", diet: "Carnivore — plankton, fish eggs, and small fish", lifespan: "Potentially immortal", speed: "8 km/h", size: "4.5 mm diameter", funFacts: ["The immortal jellyfish can revert to its juvenile state.", "Jellyfish have no brain, heart, or bones.", "They are 95% water.", "A group of jellyfish is called a bloom."] },
    { name: "Crab", scientificName: "Birgus latro", description: "The coconut crab is the world's largest land-living arthropod. It can crack open coconuts with its powerful claws and is found on islands across the Indian and Pacific Oceans.", category: "Invertebrate", status: "Vulnerable", habitat: "Tropical islands of the Indian and Pacific Oceans", diet: "Omnivore — coconuts, fruits, and carrion", lifespan: "40–60 years", speed: "4 km/h", size: "Up to 4 kg", funFacts: ["Coconut crabs crack open coconuts with bare claws.", "They have an extraordinary sense of smell.", "Young coconut crabs live in shells like hermit crabs.", "They are the largest land invertebrate on Earth."] },
    { name: "Starfish", scientificName: "Pisaster ochraceus", description: "The ochre sea star is a keystone predator in Pacific tidal ecosystems. Its removal was the first demonstration of ecological collapse, giving rise to the concept of keystone species.", category: "Invertebrate", status: "Least Concern", habitat: "Rocky intertidal zones of the Pacific coast of North America", diet: "Carnivore — mussels, barnacles, snails, and limpets", lifespan: "20 years", speed: "0.09 km/h", size: "Up to 500 grams", funFacts: ["Starfish can regenerate a lost arm — sometimes a whole body.", "They have no brain or blood — using seawater in their vascular system.", "Starfish push their stomach outside their body to digest food.", "They have eyes at the tip of each arm."] },
    { name: "Lobster", scientificName: "Homarus americanus", description: "The American lobster is one of the longest-lived marine animals. Scientists believe lobsters may not age in the traditional sense, showing no signs of reduced fertility or increased mortality with age.", category: "Invertebrate", status: "Least Concern", habitat: "Rocky ocean floors of the North Atlantic", diet: "Omnivore — fish, mollusks, algae, and detritus", lifespan: "45–50+ years", speed: "18 km/h", size: "Up to 9 kg", funFacts: ["Lobsters may be biologically immortal — they keep growing.", "They can regenerate lost claws and legs.", "Lobsters were once considered food for the poor.", "A lobster's blood is colorless — it turns blue in oxygen."] },
    { name: "Owl", scientificName: "Bubo bubo", description: "The Eurasian eagle-owl is one of the world's largest owls with a wingspan reaching 1.8 meters. They are apex nocturnal predators with exceptional low-light vision and near-silent flight.", category: "Bird", status: "Least Concern", habitat: "Rocky landscapes, forests, and mountains across Europe and Asia", diet: "Carnivore — rabbits, rodents, birds, and reptiles", lifespan: "20 years in the wild", speed: "65 km/h", size: "1.5–4.2 kg", funFacts: ["Owls can rotate their heads up to 270 degrees.", "They have asymmetrical ears for precise sound location.", "Owls fly almost silently due to comb-like feather edges.", "A group of owls is called a parliament."] },
    { name: "Bear", scientificName: "Ursus arctos", description: "The grizzly bear is one of North America's most powerful predators. They are omnivores famous for pre-hibernation hyperphagia, eating up to 20,000 calories per day to survive winter.", category: "Mammal", status: "Least Concern", habitat: "Forests, mountains, and tundra of North America and Europe", diet: "Omnivore — fish, berries, roots, insects, and small mammals", lifespan: "20–25 years in the wild", speed: "55 km/h", size: "130–360 kg", funFacts: ["Grizzly bears can smell food from 29 km away.", "They eat up to 20,000 calories per day before hibernation.", "Bears are excellent fishermen catching salmon mid-leap.", "Despite their size they can run as fast as a horse."] },
    { name: "Monkey", scientificName: "Macaca mulatta", description: "The rhesus macaque is one of the most studied primates in the world. They are highly adaptable, intelligent, and live in complex social groups. Their genetics and physiology are remarkably similar to humans.", category: "Mammal", status: "Least Concern", habitat: "Forests, grasslands, and mountain ranges across South and Southeast Asia", diet: "Omnivore — fruit, seeds, roots, and small animals", lifespan: "25–30 years", speed: "55 km/h", size: "5–7 kg", funFacts: ["Rhesus macaques were the first primates sent to space.", "They have cheek pouches to store food while foraging.", "These monkeys can recognize themselves in photographs.", "They communicate through over 30 distinct vocalizations."] },
    { name: "Llama", scientificName: "Lama glama", description: "The llama is a domesticated South American camelid, widely used as a meat and pack animal by Andean cultures since the Pre-Columbian era. They are known for their gentle nature and occasional spitting when stressed.", category: "Mammal", status: "Least Concern", habitat: "High-altitude Andean plateaus and mountains of South America", diet: "Herbivore — grasses, shrubs, and hay", lifespan: "15–25 years", speed: "56 km/h", size: "130–200 kg", funFacts: ["Llamas spit when stressed or annoyed.", "They have been used as pack animals for over 5,000 years.", "Llamas hum to communicate with each other.", "A llama can carry up to 30% of its body weight."] },
    { name: "Alpaca", scientificName: "Vicugna pacos", description: "The alpaca is a species of South American camelid. They are primarily kept for their exceptionally soft fiber, which is warmer and lighter than sheep wool. Alpacas are gentle, intelligent animals that communicate through humming.", category: "Mammal", status: "Least Concern", habitat: "High-altitude grasslands of the Andes mountains", diet: "Herbivore — grasses and hay", lifespan: "15–20 years", speed: "35 km/h", size: "48–84 kg", funFacts: ["Alpaca fiber is warmer and lighter than sheep wool.", "They communicate primarily through humming.", "Alpacas have soft padded feet that are gentle on the land.", "They live in herds and become stressed when alone."] },
    { name: "Duck", scientificName: "Anas platyrhynchos", description: "The mallard is the most recognizable and most common duck in the world. It is the ancestor of almost all domestic duck breeds. Males have the iconic iridescent green head during breeding season.", category: "Bird", status: "Least Concern", habitat: "Wetlands, ponds, rivers, and lakes worldwide", diet: "Omnivore — aquatic plants, insects, worms, and small fish", lifespan: "5–10 years in the wild", speed: "80 km/h flying", size: "0.9–1.3 kg", funFacts: ["Mallard ducks can sleep with one eye open.", "Their waterproof feathers trap air for insulation and buoyancy.", "Ducklings imprint on the first moving thing they see after hatching.", "A group of ducks on water is called a raft."] },
    { name: "Goose", scientificName: "Branta canadensis", description: "The Canada goose is one of the most recognizable waterfowl in the world. They are known for flying in V-formations during migration, which reduces wind resistance and saves energy for the whole flock.", category: "Bird", status: "Least Concern", habitat: "Lakes, ponds, and grasslands across North America", diet: "Herbivore — grasses, grains, and aquatic plants", lifespan: "10–25 years in the wild", speed: "97 km/h flying", size: "3–9 kg", funFacts: ["Canada geese fly in V-formation to reduce wind resistance by 70%.", "They mate for life and remain with their partner until death.", "Geese are surprisingly aggressive defenders of their nests.", "A group of geese in flight is called a skein."] },
    { name: "Salamander", scientificName: "Andrias davidianus", description: "The Chinese giant salamander is the world's largest amphibian, reaching up to 1.8 meters in length. They are ancient animals that have remained largely unchanged for 170 million years.", category: "Amphibian", status: "Critically Endangered", habitat: "Cold, fast-flowing rocky mountain streams of central and southern China", diet: "Carnivore — fish, frogs, crabs, and shrimp", lifespan: "50–60 years", speed: "N/A", size: "Up to 50 kg", funFacts: ["Chinese giant salamanders can reach 1.8 meters in length.", "They have remained unchanged for 170 million years.", "They breathe entirely through their skin.", "Males guard and fan the eggs until they hatch."] },
    { name: "Shrimp", scientificName: "Stenopus hispidus", description: "The banded coral shrimp is one of the ocean's most important cleaning station operators. They remove parasites and dead tissue from fish, playing a vital role in coral reef ecosystem health.", category: "Invertebrate", status: "Least Concern", habitat: "Coral reefs and rocky bottoms in tropical seas worldwide", diet: "Omnivore — parasites, algae, and detritus", lifespan: "3–4 years", speed: "N/A", size: "Up to 6 cm", funFacts: ["Banded coral shrimp set up cleaning stations on reefs.", "Fish queue up and wait their turn to be cleaned.", "They can regenerate lost claws and legs.", "Shrimp have their hearts in their heads."] },
    { name: "Squid", scientificName: "Architeuthis dux", description: "The giant squid is one of the largest invertebrates on Earth and one of the most mysterious. They inhabit the deep ocean and are known for their enormous eyes — the largest of any living animal.", category: "Invertebrate", status: "Least Concern", habitat: "Deep oceans worldwide, typically 300–1,000 meters depth", diet: "Carnivore — fish and other squid", lifespan: "5 years", speed: "25 km/h", size: "Up to 275 kg", funFacts: ["Giant squid have the largest eyes of any living animal — up to 30 cm diameter.", "They can change color using specialized skin cells.", "Giant squid arms have serrated suckers that can scar sperm whales.", "A live giant squid was not photographed until 2004."] }
];

async function fetchPexelsImages(animalName) {
    try {
        const query = `${animalName} animal wildlife`;
        const [mainRes, galleryRes] = await Promise.all([
            axios.get(`https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=1&orientation=landscape`, {
                headers: { Authorization: process.env.PEXELS_API_KEY }
            }),
            axios.get(`https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=3&orientation=landscape`, {
                headers: { Authorization: process.env.PEXELS_API_KEY }
            })
        ]);
        const image = mainRes.data.photos?.[0]?.src?.large || null;
        const gallery = galleryRes.data.photos?.map(p => p.src.large) || [];
        return { image, gallery };
    } catch (err) {
        console.error(`Pexels error for ${animalName}:`, err.message);
        return { image: null, gallery: [] };
    }
}

const seedDB = async () => {
    await connectDB();
    try {
        console.log('Clearing existing animals...');
        await Animal.deleteMany();
        console.log(`Fetching Pexels images for ${animalsData.length} animals...\n`);

        const animalsWithImages = [];
        for (const animal of animalsData) {
            process.stdout.write(`  ${animal.name}...`);
            const { image, gallery } = await fetchPexelsImages(animal.name);
            animalsWithImages.push({ ...animal, image, gallery });
            console.log(image ? ' done' : ' no image');
            await new Promise(r => setTimeout(r, 300));
        }

        await Animal.insertMany(animalsWithImages);
        console.log(`\nDone! ${animalsWithImages.length} animals seeded.`);
        process.exit();
    } catch (err) {
        console.error('Seeding error:', err);
        process.exit(1);
    }
};

seedDB();